"""Content input, upload, and generation models."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


def _new_id() -> str:
    return str(uuid.uuid4())


class Platform(str, Enum):
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    LINKEDIN = "linkedin"
    YOUTUBE = "youtube"
    FIVERR = "fiverr"
    X = "x"


class ContentType(str, Enum):
    PHOTO = "photo"
    VIDEO = "video"
    STATEMENT = "statement"
    CALENDAR_EVENT = "calendar_event"


class ContentUpload(BaseModel):
    """Raw content upload from the creator before processing."""

    id: str = Field(default_factory=_new_id)
    content_type: ContentType
    raw_content: str = Field(description="Text description, transcript, or caption of the upload.")
    file_path: str | None = Field(default=None, description="Optional path to uploaded file.")
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class IntakeAnswer(BaseModel):
    """A creator's answer to a psychological intake question."""

    question_id: str
    answer_text: str


class BrainSession(BaseModel):
    """An active Brain processing session for a creator."""

    id: str = Field(default_factory=_new_id)
    user_id: str
    uploads: list[ContentUpload] = Field(default_factory=list)
    intake_answers: list[IntakeAnswer] = Field(default_factory=list)
    current_story_context: str = Field(default="")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class GeneratedContent(BaseModel):
    """Platform-ready content generated by the Creator AI."""

    id: str = Field(default_factory=_new_id)
    platform: Platform
    content_text: str
    hashtags: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    scheduled_at: datetime | None = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
